### ISSUE TITLE
Diff with type RPM not working with remote sources

### ISSUE THREAD

**Issue by BBQigniter** [GoogleCloudPlatform/container-diff#162] opened 2017-12-11 08:15 UTC
I just built me the latest version with RPM support and tried to compare two images via our private docker repo and stumbled upon this minor issue. 
Following command works but as those images are based on centos the result is not very usefull (without and with `--type=apt`):

`./container-diff-linux-amd64 diff remote://our-repo/base/centos7_base:latest remote://our-repo/somecontainer/based_on_centos`

output (shortend)
```
Starting diff on images[...]
Computing diffs

-----Apt-----
[...]
Version differences: None
```

**But** with the addtional `type=rpm` i get:

```
Starting diff on images[...]
Computing diffs
ERRO[0007] Error getting diff with RPMAnalyzer: no such image
ERRO[0007] Could not retrieve diff: Could not perform diff on [...]
```

somehow it seems that with `--type=rpm` and using "remote", images are not pulled. If I pull the images first and replace `remote://` with `daemon://` it works as expected.

Anyway, thank you for the RPM-diff implementation!

**Comment by vrothberg** [comment] 2017-12-11 08:40
@BBQigniter I'm looking into this. Obviously, I didn't test the RPM differ with `remote://` images, but the problem is that the downloaded images aren't correctly preserved in the daemon, which is necessary in order start the containers for the RPM analysis after pulling. Thanks a lot for taking the time to report the issue!

**Comment by vrothberg** [comment] 2017-12-11 09:34
Yes, the issue is the following. `container-diff` doesn't load the referenced `remote://` image into the daemon, but it simply downloads and unpacks all blobs (see  https://github.com/GoogleCloudPlatform/container-diff/blob/master/pkg/util/image_prep_utils.go#L96) to `/tmp/`. This is sufficient for some differs, but not for the PRM one, which requires running the analysis in a container to properly execute RPM queries.

@nkubala What I suggest to do here is to write all data into a tar archive in `/tmp/`, which is then set as `Image.Source`. This way we don't mess with local images in the daemon and we reuse all logic in the RPM differ. I expect the logic in the code to get a little bit hairy as the tar archived should be removed afterward.

**Comment by nkubala** [comment] 2017-12-13 19:24
@vrothberg Thanks for looking into this. I'm a bit confused on what you're proposing; writing the data to an archive in `/tmp` is currently what we're doing already. The main issue I see is that the RPM differ needs an actual image in the local daemon to run some prerequisite commands, so we'll need to get the image into the Docker daemon before doing the diff.

Since the RPM differ already requires a running daemon (while the other differs do not), it seems to me the simplest solution here would be to just force a pull of the remote image into the local daemon and then always run the RPM differ in "local" mode. What do you think?

I do agree that at some point the pull/extract code could use a rework, but that's a much bigger refactor :)

**Comment by vrothberg** [comment] 2017-12-13 21:02
@nkubala Thanks for your reply, and sorry for the confusion! What I was proposing was to extend https://github.com/GoogleCloudPlatform/container-diff/blob/master/pkg/util/image_prep_utils.go#L96. Currently, `getFileSystemFromReference` doesn't download the tar of the referenced image as a whole, but it downloads each blob separately, unpacks it and writes it to the temporary directory. What I proposed may look as follows:

1. Generate tmp dir `foo/`
2. Download image tar to `foo/`
3. Unpack the image tar in, for instance, `foo/rootfs/`
4. Perform the analyses
5. Remove `foo/`

I think that the biggest benefit of it is that it's independent of the analyzer (and future ones can benefit from it) and that it doesn't require a running daemon.

If we pull the image, it's likely to happen in the `RPMAnalyzer` and would add yet more specific code to it. It would also imply downloading the remote image twice (once the tar and once the image).

I am okay with both (although I prefer the first). What do you think?

**Comment by nkubala** [comment] 2017-12-21 15:54
Sorry for the super late reply @vrothberg. Thanks for clearing that up, my fault for misunderstanding you. Your proposal makes sense to me, but the one thing I'm unclear on is step 2: how do we download the image tar from a remote source to the new directory? It seems like the rest of your steps assume the tar will be in the `docker save` format, but I don't know of any way to directly download an image in that format without either using docker commands, or using libraries like what we're doing now to download the individual layers. Does `skopeo`'s `containers/copy` help us do something like this?

Normally I wouldn't be big on special casing certain parts of the code, but since we've already done that for the `RPMAnalyzer` I don't think it's the end of the world to have specific logic for pulling images and loading them, since we're already running a container for that analyzer anyway. I think we could also avoid pulling the image twice, by just `docker load`ing the temp directory we download all the image layers into.

**Comment by vrothberg** [comment] 2017-12-21 16:53
@nkubala No worries, I was quite busy as well :-) Unfortunately, I won't find time until January to work on this issue, but then I can check if it's possible to download everything as suggested. Otherwise, I completely agree that we can defer the download to the already special cased `RPMAnalyzer`.

**Comment by vrothberg** [comment] 2017-12-22 09:11
@nkubala Actually, I found some time now to work on this issue before leaving into the Christmas chaos, see #164. I followed your advice to pull a `remote://` image in case it's not in the daemon. This required to extend the `Image` type a little, but I think it's sane. Due to holidays, I won't be able to work on the PR in case something must be changed. If you want to get this merged before next year, please, feel free to edit and change the PR as you desire.

**Closed** 2018-01-10 23:18 UTC
